[tools]
age = "latest"
atuin = "latest"
bat = "latest"
bat-extras = "latest"
bun = "latest"
caddy = "latest"
chezmoi = "latest"
crystal = "latest"
delta = "latest"
deno = "latest"
doctl = "latest"
elixir = "latest"
erlang = "latest"
fzf = "latest"
go = "latest"
jj = "latest"
jjui = "latest"
kubectx = "latest"
lsd = "latest"
lua = "latest"
minikube = "latest"
node = "latest"
postgres = "latest"
python = "latest"
redis = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
sqlite = "latest"
tlrc = "latest"
tmux = "latest"
watchexec = "latest"
yarn = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
